version: "3.8"

services:
  web:
    build: ./frontend
    ports:
      - 3000:3000
  web-tests:
    image: vidly_web
    volumns:
      - ./frontend:/app
    command: npm test
  api:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
      
